version: '3.8'
services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: "${BD_USERNAME}"
      POSTGRES_PASSWORD: "${BD_PASSWORD}"
      POSTGRES_DB: "${BD_DATABASE}"
    ports:
      - ${BD_PORT}:${BD_PORT}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    restart: unless-stopped